### ISSUE TITLE
2017-03-15 Meeting and Midterm Task List

### ISSUE THREAD

**Issue by ahunker** [ahunker/Hamilton-Project#5]
Regex to Wrap Speeches and Speakers:
```
Find: (\n\n)<l>\[(.+)\]</l>
Replace: </sp>\1<sp who="#"><speaker>\2</speaker>
```

**Comment by ahunker** [comment]
Things to do:
@bsf15 
- [x] Finish up-conversion of Act Two and upload to GitHub
- [ ] Write bio
- [ ] Write description of project

@ahunker
- [x] Start personography
- [x] Check distinct-values of `@who and @ref `
- [ ] Write bio
- [ ] Create list of occupations

@ebeshero 
- [x] Help figure out what's causing the w3c validator pain about the formatting, for use in perfecting the project XSLT to HTML:  https://validator.w3.org/nu/?doc=http%3A%2F%2Fhamilton.newtfire.org%2F
- [x] Add Schematron to ODD

**Comment by ebeshero** [comment]
@ebeshero @ahunker 
For Schematron rule that checks plural attribute values: here's the template we'll be following:

````
 <constraintSpec ident="checking-ref-resp-atts" scheme="isoschematron">
          <constraint>  
        <sch:pattern>
          <sch:rule context="@ref | @who">
            <sch:let name="si" value="doc('../SI-Amadis.xml')//@xml:id"/>
            <sch:let name="tokens" value="for $i in tokenize(., '\s+') return substring-after($i,'#')"/>
            <sch:assert test="every $token in $tokens satisfies $token = $si">The attribute (after the hashtag, #) must match a defined @xml:id in the Site Index file!</sch:assert>
          </sch:rule>
        </sch:pattern></constraint></constraintSpec>

````

**Comment by bsf15** [comment]
I finally added all of the converted act two xml and text files and associated the files with the ODD. I got a lot of errors on some of the files due to the multiple people within who attributes, but I believe we are fixing that in the ODD, so it will accept multiple attributes for who once that ODD gets updated, I think.

**Comment by ahunker** [comment]
Thank you! The reason why the ODD was saying your attributes was wrong is because I forgot to push the updated ODD we made on Wednesday. I'll go through your files and tag dates, people, and places and double check everything.
